# Server Ports

[adServerConfig]
port = 3014
host = "127.0.0.1"

[dataServiceConfig]
port = 3013
host = "127.0.0.1"

[dbConfig]
# nothing here yet

[iotCertificateServiceConfig]
port = 3018
host = "127.0.0.1"

[kioskInventoryServiceConfig]
port = 3017
host = "127.0.0.1"

[proxyServiceConfig]
port = 3012
host = "127.0.0.1"

[reelsConfig]
port = 3016
host = "127.0.0.1"

[transactionServiceConfig]
port = 3015
host = "127.0.0.1"

[mqttConfig]
port = 3019
host = "127.0.0.1"

# Certificate Authority Configuration
[caConfig.rootCaConfig]
common_name = "UnRedbox Root CA 1"
organization = "UnRedbox"
country = "US"
validity_years = 25

[caConfig.brokerConfig]
common_name = "*.iot.unredbox.local"
organizational_unit = "UnRedbox APIs"
organization = "UnRedbox"
locality = "Oakbrook Terrace"
state = "IL"
country = "US"
validity_years = 20

[caConfig.deviceConfig]
common_name = "UnRedbox IoT Certificate"
organizational_unit = "UnRedbox APIs"
organization = "UnRedbox"
locality = "Oakbrook Terrace"
state = "IL"
country = "US"
validity_years = 20

# Redbox Desktop + Field Maintenance Credentials

[[loginInfo.desktop]] # Redbox Desktop
username = "admin"
password = "1234"

[[loginInfo.field]] # Field Maintenance
username = "admin"
password = "1234"

# ... add any more logins here
